stages:
  - build
  - tests
  - deploy

job_build:
  stage: build
  script:
    - docker-compose build

job_test:
  stage: tests
  dependencies:
    - job_build
  script:
    - docker-compose -f docker-compose.test.yml up -d
    - pip install pytest
    - pytest
  after_script:
    - docker-compose down

job_deploy:
  stage: deploy
  only:
    - project
  script:
    - echo "Deploying to production environment"
#    SSH into EC2/cloud instance
    - docker-compose up -d
