services:
    service1:
      # Define which docker file to use
      build: ./service1
      # Map inside port to outside port
      ports:
        - "8199:8199"
      # Ensure Service2 is started before Service1
      depends_on:
        - service2
    service2:
      # Define which docker file to use
      build: ./service2
      expose:
        - "8080"